.TH template: "1" "June 2017" "template: template v0\&.1" "User Commands"

.SH "NAME"
template \- template

.SH "SYNOPSIS"
.sp
.nf
\fItemplate\fR [\-hv] [\-o \fItemplate.c\fR]
.fi

.SH "DESCRIPTION"
.sp
template

.SH "USAGE"
.sp
template

.SS "COMMANDS"
.sp
template

.SS "OPTIONS"
.sp
Command line options:

.HP
\fB\-h\fR,\fB\-\-help\fR:	Show help/usage information.
.HP
\fB\-v\fR,\fB\-\-version\fR:	Show version information.
.HP
\fB\-o\fR:			Name of the file to output source to.

.SH "NOTES"
.sp
Please direct any bug/issue reports, as well as any feature requests, to <\fIhttps://github\&.com/alyptik/template\fR>
.fi

.SH "AUTHORS"
.ie n \{\
 \h'-04'\(bu\h'+03'\c \&.\}
.el \{\
.sp -1
.IP \(bu 2\&.3
.\}
Joey Pabalinas <\fIjoeypabalinas@gmail.com\&\&.com\fR>
.fi
